---
base_url: https://jobs.academicwork.ch/advertsearch/

headers:
  user-agent:  Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36
  content-type: application/json
  requestverificationtoken: 

payload:
  SearchQueryItems:
    - type: Categories
      value: IT
      id: "20008319"
    - type: Locations
      value: Gen√®ve
      id: "20010605"
    - type: Locations
      value: Lausanne
      parent: Vaud
      Id: "20010749"
  StartIndex: 0     # pagination

raw_cookie:
